cc_binary(
  name = 'minimum_number_of_removals_to_make_mountain_array',
  srcs = [
      'minimum_number_of_removals_to_make_mountain_array.cc'
  ],
)

cc_binary(
  name = 'longest_common_subsequence',
  srcs = [
      'longest_common_subsequence.cc'
  ],
)
cc_binary(
  name = 'subtract_the_product_and_sum_of_digits_of_an_integer',
  srcs = [
      'subtract_the_product_and_sum_of_digits_of_an_integer.cc'
  ],
)

cc_binary(
  name = 'palindromic_substrings',
  srcs = [
      'palindromic_substrings.cc'
  ],
)
cc_binary(
  name = 'asteroid_collision',
  srcs = [
      'asteroid_collision.cc',
  ],
)

cc_binary(
  name = 'sort_an_array',
  srcs = [
      'sort_an_array.cc',
  ],
)

cc_binary(
  name = 'minimum_insertion_steps_to_make_a_string_palindrome',
  srcs = [
      'minimum_insertion_steps_to_make_a_string_palindrome.cc',
  ],
)

cc_test(
  name = 'my_test',
  srcs = [
      'test/test_main.cc',
      'test/minimum_swap_to_make_strings_equal_test.cc',
  ],
  deps = [
    '//third_party/gtest:gtest'
  ],
)
