cc_binary(
  name = 'minimum_number_of_removals_to_make_mountain_array',
  srcs = [
      'dynamic_programing/minimum_number_of_removals_to_make_mountain_array.cc'
  ],
)

cc_binary(
  name = 'longest_common_subsequence',
  srcs = [
      'dynamic_programing/longest_common_subsequence.cc'
  ],
)
cc_binary(
  name = 'subtract_the_product_and_sum_of_digits_of_an_integer',
  srcs = [
      'other/subtract_the_product_and_sum_of_digits_of_an_integer.cc'
  ],
)

cc_binary(
  name = 'palindromic_substrings',
  srcs = [
      'dynamic_programing/palindromic_substrings.cc'
  ],
)
cc_binary(
  name = 'asteroid_collision',
  srcs = [
      'stack/asteroid_collision.cc',
  ],
)

cc_binary(
  name = 'minimum_insertion_steps_to_make_a_string_palindrome',
  srcs = [
      'dynamic_programing/minimum_insertion_steps_to_make_a_string_palindrome.cc',
  ],
)

cc_test(
  name = 'my_test',
  srcs = [
      'test/test_main.cc',
      'test/minimum_swap_to_make_strings_equal_test.cc',
      'test/sort_an_array_test.cc',
      'test/verify_preorder_serialization_of_a_binary_tree_test.cc',
      'test/generate_parentheses_test.cc',
  ],
  deps = [
    '//third_party/gtest:gtest'
  ],
)
